language: node_js
node_js:
- "8"
- "10"
- "lts"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"

cache: yarn

before_script: "yarn install"

jobs:
  fail_fast: true
  include:
  - stage: "Quality"
    name: "Linting"
    script: yarn lint:js


script: "yarn test"
