language: node_js
node_js:
- "8"
- "10"
- "latest"

cache: yarn

before_script: "yarn install"

jobs:
  fail_fast: true
  include:
  - stage: "Quality"
    name: "Linting"
    script: yarn lint:js


script: "yarn test"
